apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    azure-pipelines/jobName: '"Deploy da Imagem no Cluster"'
    azure-pipelines/org: https://brasilterminalportuario.visualstudio.com/
    azure-pipelines/pipeline: '"worker-codesp-diario"'
    azure-pipelines/pipelineId: '"311"'
    azure-pipelines/project: Worker Project
    azure-pipelines/run: "20230426.9"
    azure-pipelines/runuri: https://brasilterminalportuario.visualstudio.com/Worker
      Project/_build/results?buildId=24453
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"azure-pipelines/jobName":"\"Deploy da Imagem no Cluster\"","azure-pipelines/org":"https://brasilterminalportuario.visualstudio.com/","azure-pipelines/pipeline":"\"worker-codesp-diario\"","azure-pipelines/pipelineId":"\"311\"","azure-pipelines/project":"Worker Project","azure-pipelines/run":"20230426.9","azure-pipelines/runuri":"https://brasilterminalportuario.visualstudio.com/Worker Project/_build/results?buildId=24453","deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2023-10-30T18:17:47Z","generation":1,"labels":{"app.project.name":"workercodespdiario","app.report":"operacional"},"name":"deployment-workercodespdiario","namespace":"btp-external-dev","resourceVersion":"6321962","uid":"1aec62e5-0d37-425d-91d7-dcf8fb54499f"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"workercodespdiario"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"workercodespdiario"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["codespdiario"]}]},"topologyKey":"topology.kubernetes.io/hostname"},"weight":100}]}},"containers":[{"env":[{"name":"DOTNET_ENVIRONMENT","value":"Development"}],"image":"registrybtp.azurecr.io/workercodespdiario:dev-24453","imagePullPolicy":"IfNotPresent","name":"codespdiario","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/app/tnsnames.ora","name":"tns-oracle","subPath":"tnsnames.ora"},{"mountPath":"/app/share","name":"data-template"},{"mountPath":"/app/share-nfs","name":"data-template-test-nfs"},{"mountPath":"/app/share/smb-test","name":"data-template-test-smb"}]}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"workercodespdiario-auth"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"tns-oracle","secret":{"defaultMode":420,"secretName":"conexao-oracle"}},{"name":"data-template","persistentVolumeClaim":{"claimName":"cifs-codesp-diario-dev"}},{"name":"data-template-test-nfs","persistentVolumeClaim":{"claimName":"test-nfs-pvc"}},{"name":"data-template-test-smb","persistentVolumeClaim":{"claimName":"test-smb-pvc"}}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2023-10-30T18:17:59Z","lastUpdateTime":"2023-10-30T18:17:59Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-10-30T18:17:47Z","lastUpdateTime":"2023-10-30T18:17:59Z","message":"ReplicaSet \"deployment-workercodespdiario-75c84b4444\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2023-10-31T15:16:14Z"
  generation: 1
  labels:
    app.project.name: workercodespdiario
    app.report: operacional
  name: deployment-workercodespdiario
  namespace: btp-external-dev
  resourceVersion: "6912713"
  uid: 54b89369-2356-497f-ac96-dd7d34e354c5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: workercodespdiario
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: workercodespdiario
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - codespdiario
              topologyKey: topology.kubernetes.io/hostname
            weight: 100
      containers:
      - env:
        - name: DOTNET_ENVIRONMENT
          value: Development
        image: registrybtp.azurecr.io/workercodespdiario:dev-24453
        imagePullPolicy: IfNotPresent
        name: codespdiario
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/tnsnames.ora
          name: tns-oracle
          subPath: tnsnames.ora
        - mountPath: /app/share
          name: data-template
        - mountPath: /app/share-nfs
          name: data-template-test-nfs
        - mountPath: /app/share/smb-test
          name: data-template-smb
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: workercodespdiario-auth
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: tns-oracle
        secret:
          defaultMode: 420
          secretName: conexao-oracle
      - name: data-template
        persistentVolumeClaim:
          claimName: cifs-codesp-diario-dev
      - name: data-template-test-nfs
        persistentVolumeClaim:
          claimName: test-nfs-pvc
      - name: data-template-smb
        persistentVolumeClaim:
          claimName: test-pvc-smb
status:
  conditions:
  - lastTransitionTime: "2023-10-31T15:16:14Z"
    lastUpdateTime: "2023-10-31T15:16:14Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-10-31T16:58:45Z"
    lastUpdateTime: "2023-10-31T16:58:45Z"
    message: ReplicaSet "deployment-workercodespdiario-865cbb9759" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
